optimizer:
  name: adam
  lr: 1.0e-3
  weight_decay: 0

train:
  epoch: 3000
  batch_size: 4096
  save_model: true
  test_step: 1
  reproducible: true
  seed: 2023
  patience: 20

test:
  metrics: [recall, ndcg]
  k: [5, 10, 20, 50]
  batch_size: 1024

data:
  type: general_cf

model:
  name: default

