optimizer:
  name: adam
  lr: 1.0e-3
  weight_decay: 0

train:
  epoch: 3000
  batch_size: 4096
  save_model: true
  loss: pairwise
  log_loss: false
  test_step: 1
  reproducible: true
  seed: 2023
  patience: 20

test:
  metrics: [recall, ndcg]
  k: [5, 10, 20, 50]
  batch_size: 1024

data:
  type: general_cf
  name: games

model:
  name: lightgcn_gene
  # general parameters here
  keep_rate: 1.0
  embedding_size: 32

  # dataset-specific parameters here
  layer_num: 3
  reg_weight: 1.0e-7

  mask_ratio: 0.1
  recon_weight: 1.0e-1
  recon_tau: 0.2

